spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=portfolio_db
server.port=${PORT:8080}
spring.application.name=profolio

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nnnagarajan16@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Your email to receive notifications
app.notification.email=${NOTIFICATION_EMAIL}

# MongoDB SSL fix
spring.data.mongodb.ssl.enabled=true
